name: Build and Scan Docker Image

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
     
    steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Build and Push Bckend
       shell: bash
       run: |
        docker build -t my-node-app .

     - name: Docker Scout
       id: docker-scout
       uses: docker/scout-action@dd36f5b0295baffa006aa6623371f226cc03e506
       with:
          command: cves
          image: my-node-app
          token: "dckr_pat_8kck2x2NHpG5jUFJQ01t1W80k-E"
          only-severities: critical
          exit-code: true
