name: Build and Scan Docker Image

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
     
    steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Build and Push Bckend
       shell: bash
       run: |
        docker build -t my-node-app .

     - name: Docker Scout
       id: docker-scout
       if: ${{ github.event_name != 'pull_request_target' }}
       uses: docker/scout-action@v1
       with:
          command: cves
          image: my-node-app
          only-severities: low
          exit-code: true
          dockerhub-user: gora04
          dockerhub-password: N@z@r2027
