name: Build and Scan Docker Image

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
     
    steps:
     - name: Checkout code
       uses: actions/checkout@v2
       
     - name: Login to ACR
       uses: docker/login-action@v3
       with:
          registry: sbxbccommonacr.azurecr.io
          username: sbxbccommonacr
          password: lyf3Gg4Vf5pXfxFLNwtHiPhAOistI1K0gO8hUMLde2+ACRCKfUCa

     - name: Build and Push Bckend
       shell: bash
       run: |
        docker build -t my-node-app .
        docker tag my-node-app sbxbccommonacr.azurecr.io/my-node-app
        docker push sbxbccommonacr.azurecr.io/my-node-app

     - name: Docker Scout
       id: docker-scout
       if: ${{ github.event_name != 'pull_request_target' }}
       uses: docker/scout-action@v1
       with:
          command: cves
          image: my-node-app
          only-severities: low
          exit-code: true
          registry-user: nazar
          registry-password: lyf3Gg4Vf5pXfxFLNwtHiPhAOistI1K0gO8hUMLde2+ACRCKfUCa
          #github-token: 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
          #dockerhub-user: gora04
          #dockerhub-password: N@z@r2027
