name: Build and Scan Docker Image

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
     
    steps:
     - name: Checkout code
       uses: actions/checkout@v2
     - name: Login to ACR
       uses: docker/login-action@v3
       with:
          registry: error123.azurecr.io
          username: error123
          password: qjsz8skkiQOSbwwV2Mf+NMrN2gfxcjEhAp0Oqur60f+ACRDvIj61
       
     - name: Run Docker Scout
       run: |
          docker scout cves error123.azurecr.io/my-node-app:latest
       
          
